# This is a sample build configuration for Ruby.
# Check our guides at https://confluence.atlassian.com/x/8r-5Mw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: ruby:2.4.1

pipelines:
  default:
    - step:
        caches:
          - bundler
        script: # Modify the commands below to build your repository.
          - export DATABASE_URL=postgresql://ds02_server_test:ds02_server_test@localhost/ds02_server_test
          - apt-get update -y
          - apt-get install -y build-essential git-core curl nodejs libmysqlclient-dev ssh
          - gem install rails
          - gem install bundler
          - bundle install
          - cp config/secrets.ci.yml config/secrets.yml
          - cp config/database.ci.yml config/database.yml
          - bundle exec rake db:migrate RAILS_ENV=test
          - rspec
        services:
          - postgres
 
definitions:
  services:
    postgres:
      image: postgres
      environment:
        POSTGRES_DB: ds02_server_test
        POSTGRES_USER: ds02_server_test
        POSTGRES_PASSWORD: ds02_server_test
  caches:
    bundler: ./vendor