image: buildpals/ds02_server:0.0.1
clone:
  depth: full
pipelines:
  default:
    - step:
        script: # Modify the commands below to build your repository.
          - export DATABASE_URL=postgresql://test_user:test_user_password@localhost/pipelines
          - bundle install
          - rake db:setup
          # - rake db:test:prepare
          # - rspec
        services:
          - postgres

  branches:
    develop:
      - step:
          script: # Modify the commands below to build your repository.
            - export DATABASE_URL=postgresql://test_user:test_user_password@localhost/pipelines
            - bundle install
            - rake db:setup
            # - rake db:test:prepare
            # - rspec
            - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git develop:master
          services:
            - postgres

    staging:
      - step:
          script: # Modify the commands below to build your repository.
            - export DATABASE_URL=postgresql://test_user:test_user_password@localhost/pipelines
            - bundle install
            - rake db:setup
            # - rake db:test:prepare
            # - rspec
          services:
            - postgres

    master:
      - step:
          script: # Modify the commands below to build your repository.
            - export DATABASE_URL=postgresql://test_user:test_user_password@localhost/pipelines
            - bundle install
            - rake db:setup
            # - rake db:test:prepare
            # - rspec
          services:
            - postgres


definitions:
  services:
    postgres:
      image: postgres
      environment:
        POSTGRES_DB: pipelines
        POSTGRES_USER: test_user
        POSTGRES_PASSWORD: test_user_password