development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:737b7cad74ea813ab5a56ee2b41e0b45@tarpon.redistogo.com:11999/
  channel_prefix: ds02_server_production
